name: Deploy

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: DEPLOYMENT
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          debug: true
          script: |
            echo "START DEPLOYMENT"
            cd flipclouds
            git pull
            docker-compose run --rm composer install --no-dev
            docker-compose run --rm artisan migrate
            echo "END DEPLOYMENT"
          
